# Generated by Django 5.0.6 on 2024-07-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numDecl', models.CharField(max_length=50)),
                ('annDecl', models.PositiveIntegerField()),
                ('jourDecl', models.PositiveIntegerField()),
                ('moisDecl', models.PositiveIntegerField()),
                ('heurDecl', models.DateField()),
                ('langDecl', models.CharField(max_length=255)),
                ('lieDecl', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Declarant',
            fields=[
                ('idD', models.AutoField(primary_key=True, serialize=False)),
                ('nomD', models.CharField(max_length=100)),
                ('qualiteD', models.CharField(max_length=100)),
                ('lieNceD', models.CharField(max_length=155)),
                ('datNceD', models.DateTimeField(blank=True)),
                ('profD', models.CharField(max_length=255)),
                ('adresD', models.CharField(max_length=255)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarants', to='officier.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEnf', models.CharField(max_length=100)),
                ('jourNceEnf', models.PositiveIntegerField()),
                ('moiNceEnf', models.PositiveIntegerField()),
                ('annNceEnf', models.PositiveIntegerField()),
                ('heureNceEnf', models.TimeField()),
                ('lieNceEnf', models.CharField(max_length=255)),
                ('sexNceEnf', models.CharField(max_length=255)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='officier.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('idM', models.AutoField(primary_key=True, serialize=False)),
                ('nomM', models.CharField(max_length=100)),
                ('lieNceM', models.CharField(max_length=100)),
                ('datNceM', models.DateTimeField(blank=True)),
                ('natM', models.CharField(max_length=255)),
                ('profM', models.CharField(max_length=255)),
                ('adresM', models.CharField(max_length=255)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meres', to='officier.declaration')),
            ],
        ),
        migrations.CreateModel(
            name='Pere',
            fields=[
                ('idP', models.AutoField(primary_key=True, serialize=False)),
                ('nomP', models.CharField(max_length=100)),
                ('lieNceP', models.CharField(max_length=100)),
                ('datNceP', models.DateTimeField(blank=True)),
                ('natP', models.CharField(max_length=255)),
                ('profP', models.CharField(max_length=255)),
                ('adresP', models.CharField(max_length=255)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peres', to='officier.declaration')),
            ],
        ),
    ]
