# Generated by Django 5.0.6 on 2024-07-27 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant',
            name='annNceEnf',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='jourNceEnf',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='moiNceEnf',
        ),
        migrations.AddField(
            model_name='enfant',
            name='dateNceEnf',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='enfant',
            name='numero',
            field=models.IntegerField(default='00000', max_length=10),
        ),
    ]
