# Generated by Django 5.0.6 on 2024-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officier', '0002_remove_enfant_annnceenf_remove_enfant_journceenf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarant',
            name='prenomD',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='mere',
            name='prenomM',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='pere',
            name='prenomP',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AlterField(
            model_name='enfant',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
